# Generated by Django 5.2.6 on 2026-09-16 09:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operators", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="data",
        ),
        migrations.RemoveField(
            model_name="project",
            name="dcr_project_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="title",
        ),
        migrations.AddField(
            model_name="project",
            name="certification_scheme_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="project",
            name="certification_scheme_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="project",
            name="cobenefits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="project",
            name="dcr_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="project",
            name="dcr_sync_status",
            field=models.CharField(
                choices=[
                    ("local", "Local only"),
                    ("synced", "Synced with DCR"),
                    ("failed", "Last sync failed"),
                ],
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="dcr_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="media_links",
            field=models.JSONField(blank=True, default=list, help_text="List of URLs"),
        ),
        migrations.AddField(
            model_name="project",
            name="methodologies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="monitoring_period_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="monitoring_period_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="monitoring_period_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="operators.operator",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies_practices_processes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of practice/process identifiers"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="term_commitment",
            field=models.PositiveIntegerField(blank=True, help_text="Years", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("CARBON_FARMING", "Carbon farming"),
                    ("CARBON_STORAGE_IN_PRODUCTS", "Carbon storage in products"),
                    ("PERMANENT_CARBON_REMOVAL", "Permanent carbon removal"),
                ],
                default="CARBON_FARMING",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="unit_types",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="ActivityPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dcr_id", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "dcr_sync_status",
                    models.CharField(
                        choices=[
                            ("local", "Local only"),
                            ("synced", "Synced with DCR"),
                            ("failed", "Last sync failed"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                ("dcr_synced_at", models.DateTimeField(blank=True, null=True)),
                ("dcr_response", models.JSONField(blank=True, default=dict)),
                ("date_submitted", models.DateField(blank=True, null=True)),
                ("activity_eligibility", models.TextField(blank=True)),
                ("legal_parcel_ownership", models.TextField(blank=True)),
                (
                    "coordinate_reference_system",
                    models.CharField(default="EPSG:4326", max_length=32),
                ),
                ("iacs_codes", models.JSONField(blank=True, default=list)),
                ("lpis_codes", models.JSONField(blank=True, default=list)),
                ("article_8_1_information", models.TextField(blank=True)),
                ("methodology_quantification_baseline", models.TextField(blank=True)),
                ("methodology_additionality_funding_sources", models.TextField(blank=True)),
                ("methodology_long_term_storage", models.TextField(blank=True)),
                ("methodology_sustainability", models.TextField(blank=True)),
                (
                    "expected_total_carbon_removals",
                    models.IntegerField(blank=True, help_text="tCO2e", null=True),
                ),
                (
                    "expected_total_soil_emissions",
                    models.IntegerField(blank=True, help_text="tCO2e", null=True),
                ),
                (
                    "expected_total_ghg_emissions_associated",
                    models.IntegerField(blank=True, help_text="tCO2e", null=True),
                ),
                (
                    "expected_net_benefit",
                    models.IntegerField(blank=True, help_text="tCO2e", null=True),
                ),
                ("group_advisory_services_description", models.TextField(blank=True)),
                ("group_internal_control_system_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonitoringPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dcr_id", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "dcr_sync_status",
                    models.CharField(
                        choices=[
                            ("local", "Local only"),
                            ("synced", "Synced with DCR"),
                            ("failed", "Last sync failed"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                ("dcr_synced_at", models.DateTimeField(blank=True, null=True)),
                ("dcr_response", models.JSONField(blank=True, default=dict)),
                ("date_submitted", models.DateField(blank=True, null=True)),
                (
                    "monitored_data_parameters",
                    models.JSONField(
                        blank=True, default=list, help_text="List of {name, unit, scope}"
                    ),
                ),
                (
                    "monitoring_frequency",
                    models.PositiveIntegerField(blank=True, help_text="Months", null=True),
                ),
                ("emission_sources_and_sinks", models.TextField(blank=True)),
                ("data_source", models.TextField(blank=True)),
                (
                    "measurement_methods_procedures_accuracy_calibration",
                    models.TextField(blank=True),
                ),
                ("quality_assessment_or_quality_control_procedures", models.TextField(blank=True)),
                ("responsibility_for_collection_and_archiving", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_plan",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
