# Generated by Django 5.2.6 on 2026-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_data_remove_project_dcr_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dcr_status_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dcr_verification',
            field=models.JSONField(blank=True, default=dict, help_text='Latest activity_verification record from DCR'),
        ),
    ]
