# Generated by Django 5.2.6 on 2026-09-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_dcr_status_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('CARBON_FARMING', 'Carbon farming'), ('CARBON_STORAGE_IN_PRODUCTS', 'Carbon storage in products'), ('PERMANENT_REMOVAL', 'Permanent carbon removal')], default='CARBON_FARMING', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit_types',
            field=models.CharField(blank=True, choices=[('Permanent Removal', 'Permanent Removal'), ('Carbon Farming Sequestration', 'Carbon Farming Sequestration'), ('Soil Emission Reduction', 'Soil Emission Reduction'), ('Carbon Storage in Product', 'Carbon Storage in Product')], help_text='Unit category produced by the activity; determines type', max_length=100),
        ),
    ]
