# Generated by Django 5.2.17 on 2026-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_type_alter_project_unit_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='expected_net_benefit',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='tCO2e', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='expected_total_carbon_removals',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='tCO2e', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='expected_total_ghg_emissions_associated',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='tCO2e', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='expected_total_soil_emissions',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='tCO2e', max_digits=14, null=True),
        ),
    ]
