# Generated by Django 5.2.17 on 2026-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_activityplan_expected_net_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
    ]
