# Generated by Django 5.2.17 on 2026-09-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dcr_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Last /users/current payload from DCR (incl. entitlements)'),
        ),
    ]
