# Generated by Django 5.2.6 on 2026-09-16 09:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('projects', '0002_remove_project_data_remove_project_dcr_project_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcr_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('dcr_sync_status', models.CharField(choices=[('local', 'Local only'), ('synced', 'Synced with DCR'), ('failed', 'Last sync failed')], default='local', max_length=16)),
                ('dcr_synced_at', models.DateTimeField(blank=True, null=True)),
                ('dcr_response', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, help_text='Local label shown in the UI', max_length=255)),
                ('cadastral_reference', models.CharField(blank=True, db_index=True, help_text='Cadastre identifier (e.g. French IDU)', max_length=64)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('iacs_codes', models.JSONField(blank=True, default=list)),
                ('lpis_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parcels', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='operators.operator')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelOwnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcr_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('dcr_sync_status', models.CharField(choices=[('local', 'Local only'), ('synced', 'Synced with DCR'), ('failed', 'Last sync failed')], default='local', max_length=16)),
                ('dcr_synced_at', models.DateTimeField(blank=True, null=True)),
                ('dcr_response', models.JSONField(blank=True, default=dict)),
                ('status_code', models.CharField(choices=[('in_progress', 'In progress'), ('verified', 'Verified'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('parcel_owner_legal_name', models.CharField(blank=True, max_length=255)),
                ('authority', models.CharField(blank=True, help_text='Authority that verified the ownership', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verification', to='parcels.parcel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcr_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('dcr_sync_status', models.CharField(choices=[('local', 'Local only'), ('synced', 'Synced with DCR'), ('failed', 'Last sync failed')], default='local', max_length=16)),
                ('dcr_synced_at', models.DateTimeField(blank=True, null=True)),
                ('dcr_response', models.JSONField(blank=True, default=dict)),
                ('status_code', models.CharField(choices=[('in_progress', 'In progress'), ('verified', 'Verified'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('amount', models.IntegerField(blank=True, help_text='Carbon reduction calculated for this parcel (tCO2e)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='parcels.parcel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_links', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'parcel')},
            },
        ),
    ]
