# Generated by Django 5.2.6 on 2026-09-16 11:02

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('parcels', '0001_initial'),
        ('projects', '0002_remove_project_data_remove_project_dcr_project_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ownership_proof', 'Proof of ownership'), ('land_use_agreement', 'Land use agreement / lease'), ('cadastral_extract', 'Cadastral extract'), ('methodology', 'Methodology / quantification'), ('monitoring_report', 'Monitoring report'), ('photo', 'Photo'), ('map', 'Map / geodata'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.documents.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=127)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('forward_status', models.CharField(choices=[('local', 'Stored locally'), ('forwarded', 'Forwarded'), ('failed', 'Forwarding failed')], default='local', max_length=16)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('forward_reference', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, help_text='Derived from the project or parcel at upload time', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='operators.operator')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parcels.parcel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
