# Generated by Django 5.2.6 on 2026-09-16 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dcr_id", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "dcr_sync_status",
                    models.CharField(
                        choices=[
                            ("local", "Local only"),
                            ("synced", "Synced with DCR"),
                            ("failed", "Last sync failed"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                ("dcr_synced_at", models.DateTimeField(blank=True, null=True)),
                ("dcr_response", models.JSONField(blank=True, default=dict)),
                ("legal_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("postcode", models.CharField(blank=True, max_length=32)),
                ("country_code", models.CharField(help_text="ISO 3166-1 alpha-2", max_length=2)),
                ("ogcr_wallet_address", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="OperatorMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dcr_id", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "dcr_sync_status",
                    models.CharField(
                        choices=[
                            ("local", "Local only"),
                            ("synced", "Synced with DCR"),
                            ("failed", "Last sync failed"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                ("dcr_synced_at", models.DateTimeField(blank=True, null=True)),
                ("dcr_response", models.JSONField(blank=True, default=dict)),
                (
                    "relationship",
                    models.CharField(
                        default="Employee",
                        help_text="How the user relates to the operator, e.g. Managing Director, Employee",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="operators.operator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["operator", "user"],
                "unique_together": {("operator", "user")},
            },
        ),
        migrations.AddField(
            model_name="operator",
            name="members",
            field=models.ManyToManyField(
                related_name="operators",
                through="operators.OperatorMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
